#!/usr/bin/env sh

HOMEDIR=~

# cp with prompt if enabled
copy(){
	cp -i $1 $2
}

# VIM settings
if ["$VIMDIR" == ""]; then
	VIMDIR=$HOMEDIR/.vim
fi
cd vim
for f in */; do
	mkdir -p $VIMDIR/$f
done
for f in */*.vim; do
	cp $f $VIMDIR/$f
done
copy rc $HOMEDIR/.vimrc
cd ..

if [ ! -f $VIMDIR/bundle/vundle ]; then
	git clone https://github.com/gmarik/vundle.git $VIMDIR/bundle/vundle
	vim "+BundleInstall" "+qall"
fi

# Shell settings
cp shell/inputrc $HOMEDIR/.inputrc
copy ssh/config $HOMEDIR/.ssh/config

mkdir -p $HOMEDIR/.config/xcolors
cp urxvt/thayer $HOMEDIR/.config/xcolors
cp urxvt/xdefaults $HOMEDIR/.Xdefaults
